### ISSUE TITLE
Model trained with 20 degree angle orientation prior.

### ISSUE THREAD

**Issue by liguopeng0923** [tudelft-iv/CCVPE#1]
Hi zimin,

I find you may not provide the model trained with 20 degree angle orientation prior. I hope you can provide them, which is helpful to reproduce corresponding results.

Best wishes,
Guopeng.

**Comment by ZiminXia** [comment]
Hi Guopeng,

Sure, I will provide it soon.

Best regards,
Zimin

**Comment by ZiminXia** [comment]
FYI, the KITTI model trained with 20-degree orientation prior is now provided.
