### ISSUE TITLE
Oxford model and training / testing script

### ISSUE THREAD

**Issue by nstannartz** [tudelft-iv/CCVPE#2]
Hello,

thanks, for uploading this repo! Would it be possible that you upload the training / testing script for the trained Oxford model as well as a corresponding updated version of the models.py for reproducibility?

Thanks and best regards,
Niklas

**Comment by ZiminXia** [comment]
Hello Niklas,

Yes. I will provide the trained model and scripts.

Best regards,
Zimin

**Comment by ZiminXia** [comment]
The code for training and testing on Oxford RobotCar is now available.
