### ISSUE TITLE
--ori_noise  for VIGOR meet ERROR

### ISSUE THREAD

**Issue by guanfang12** [tudelft-iv/CCVPE#5]
File "/mnt/afs/xurunsen/Data/CCVPE/datasets.py", line 169, in __getitem__
    gt_with_ori[20-index, :, :] = np.exp(-( (d-mu)**2 / ( 2.0 * sigma**2 ) ) ) * (1-ratio)

When rotation_range is negative, the 'index' will be negative, and there will be a problem here.

Maybe suggestion:
        # generate a random rotation 
        if self.ori_noise >= 180:
            rotation = np.random.uniform(low=0.0, high=1.0) # 
        else:
            rotation_range = self.ori_noise / 360
            rotation = np.random.uniform(low=-rotation_range, high=rotation_range)
        grd = torch.roll(grd, (torch.round(torch.as_tensor(rotation)*grd.size()[2]).int()).item(), dims=2)
                
        orientation_angle = rotation * 360 # 0 means heading North, counter-clockwise increasing

====>
        # generate a random rotation 
        rotation_range = self.ori_noise
        temp = np.random.uniform(-1, 1) 
        if temp >= 0:
            rotation = temp * rotation_range/360
        else:
            rotation = (1+temp) * rotation_range/360
        grd = torch.roll(grd, (torch.round(torch.as_tensor(rotation)*grd.size()[2]).int()).item(), dims=2)
                
        orientation_angle = rotation * 360 # 0 means heading North, counter-clockwise increasing

**Comment by ZiminXia** [comment]
Thank you for noticing this.
Including the orientation prior is a special test case and the "gt_with_ori" will not be used during testing. During training, the ground truth orientation is known and we always rotate the ground image by 0-360 degrees on the VIGOR dataset.

I just added an if statement to make sure the "gt_with_ori" is filled only during training.
